[package]
name = "todocol"
version = "0.1.0"
authors = ["Rafal Ulko <rafal.ulko@gmail.com>"]
edition = "2018"
description = "App is collecting 'TODO:' (or other) comments from project source files into one file"

[dependencies]
log = "0.4"
env_logger = "0.6"
clap = "2.33.0"
config = "0.10.1"
simple-error = "0.2.1"
shellexpand = "1.0.0"
# tokio = { version = "0.2.4", features = ["full"] }